# The URL the site will be built for
base_url = "https://cesar.enrique.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

# Config settings for theme apollo
#
# See this for more options:
# https://github.com/not-matthias/apollo/blob/main/config.toml#L14
theme = "auto"
socials = [
  # Configure socials here
]
menu = [
  # Configure menu bar here
]
