# The URL the site will be built for
base_url = "https://caenrique.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# theme = "apollo"
taxonomies = [{ name = "tags" }]
title = "Cesar Enrique"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]

[markdown.highlighting]
light_theme = "catppuccin-latte"
dark_theme = "catppuccin-mocha"
# style = "class"

[extra]
# Put all your custom variables here

# Config settings for theme apollo
#
# See this for more options:
# https://github.com/not-matthias/apollo/blob/main/config.toml#L14
socials = [
  { name = "github", url = "https://github.com/caenrique/", icon = "github" },
]
menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/talks", url = "/talks", weight = 2 },
  # { name = "/projects", url = "/projects", weight = 2 },
  { name = "/about", url = "/about", weight = 3 },
  # { name = "/tags", url = "/tags", weight = 4 },
]
mathjax_dollar_inline_enable = true
mathjax = true
toc = true
fancy_code = true
